spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: libraries
  session:
    store-type: none
  datasource:
    url: "jdbc:postgresql://postgres-libraries:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate